name: F1 Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: Script ausführen
        run: python script.py

      - name: 2 Minuten warten
        run: sleep 120

      - name: Workflow erneut starten
        run: |
          curl -X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
https://api.github.com/repos/${{ github.repository }}/actions/workflows/f1test.yml/dispatches \
-d '{"ref":"main"}'
